// eslint-disable-next-line no-unused-vars
const guildTech = {
	'Warrior': {
		hpPercent: { hpPercent: 0.005 },
		attackPercent: { attackPercent: 0.005 },
		crit: { crit: 0.005 },
		block: { block: 0.005 },
		skillDamage: { skillDamage: 0.01 },
		speed: { speed: 4 },
		constitution: { hpPercent: 0.01, attackPercent: 0.01 },
		mind: { hpPercent: 0.01, skillDamage: 0.01 },
		antiMage: { mageReduce: 0.01 },
		antiRanger: { rangerReduce: 0.01 },
		antiAssassin: { assassinReduce: 0.01 },
		antiPriest: { priestReduce: 0.01 },
		heartOfCrystal: { 'Seal of LightImmune': 0.01, ShapeshiftImmune: 0.01 },
		immortalRoar: { TauntImmune: 0.01, DazzleImmune: 0.01 },
		spellOfAgility: { petrifyImmune: 0.01, twineImmune: 0.01, HorrifyImmune: 0.01 },
		blessingOfPurification: { stunImmune: 0.01, freezeImmune: 0.01, SilenceImmune: 0.01 },
	},
	'Mage': {
		hpPercent: { hpPercent: 0.005 },
		attackPercent: { attackPercent: 0.005 },
		crit: { crit: 0.005 },
		precision: { precision: 0.005 },
		skillDamage: { skillDamage: 0.01 },
		speed: { speed: 4 },
		constitution: { hpPercent: 0.01, attackPercent: 0.01 },
		mind: { hpPercent: 0.01, skillDamage: 0.01 },
		antiWarrior: { warriorReduce: 0.01 },
		antiRanger: { rangerReduce: 0.01 },
		antiAssassin: { assassinReduce: 0.01 },
		antiPriest: { priestReduce: 0.01 },
		heartOfCrystal: { 'Seal of LightImmune': 0.01, ShapeshiftImmune: 0.01 },
		immortalRoar: { TauntImmune: 0.01, DazzleImmune: 0.01 },
		spellOfAgility: { petrifyImmune: 0.01, twineImmune: 0.01, HorrifyImmune: 0.01 },
		blessingOfPurification: { stunImmune: 0.01, freezeImmune: 0.01, SilenceImmune: 0.01 },
	},
	'Ranger': {
		hpPercent: { hpPercent: 0.005 },
		attackPercent: { attackPercent: 0.005 },
		block: { block: 0.005 },
		precision: { precision: 0.005 },
		skillDamage: { skillDamage: 0.01 },
		speed: { speed: 4 },
		constitution: { hpPercent: 0.01, attackPercent: 0.01 },
		mind: { hpPercent: 0.01, skillDamage: 0.01 },
		antiWarrior: { warriorReduce: 0.01 },
		antiMage: { mageReduce: 0.01 },
		antiAssassin: { assassinReduce: 0.01 },
		antiPriest: { priestReduce: 0.01 },
		heartOfCrystal: { 'Seal of LightImmune': 0.01, ShapeshiftImmune: 0.01 },
		immortalRoar: { TauntImmune: 0.01, DazzleImmune: 0.01 },
		spellOfAgility: { petrifyImmune: 0.01, twineImmune: 0.01, HorrifyImmune: 0.01 },
		blessingOfPurification: { stunImmune: 0.01, freezeImmune: 0.01, SilenceImmune: 0.01 },
	},
	'Assassin': {
		hpPercent: { hpPercent: 0.005 },
		critDamage: { critDamage: 0.005 },
		crit: { crit: 0.005 },
		armorBreak: { armorBreak: 0.005 },
		skillDamage: { skillDamage: 0.01 },
		speed: { speed: 4 },
		constitution: { hpPercent: 0.01, attackPercent: 0.01 },
		mind: { hpPercent: 0.01, skillDamage: 0.01 },
		antiWarrior: { warriorReduce: 0.01 },
		antiMage: { mageReduce: 0.01 },
		antiRanger: { rangerReduce: 0.01 },
		antiPriest: { priestReduce: 0.01 },
		heartOfCrystal: { 'Seal of LightImmune': 0.01, ShapeshiftImmune: 0.01 },
		immortalRoar: { TauntImmune: 0.01, DazzleImmune: 0.01 },
		spellOfAgility: { petrifyImmune: 0.01, twineImmune: 0.01, HorrifyImmune: 0.01 },
		blessingOfPurification: { stunImmune: 0.01, freezeImmune: 0.01, SilenceImmune: 0.01 },
	},
	'Priest': {
		hpPercent: { hpPercent: 0.005 },
		block: { block: 0.005 },
		crit: { crit: 0.005 },
		speed: { speed: 2 },
		skillDamage: { skillDamage: 0.01 },
		speed2: { speed: 1, attackPercent: 0.005 },
		constitution: { hpPercent: 0.01, attackPercent: 0.01 },
		mind: { hpPercent: 0.01, skillDamage: 0.01 },
		antiWarrior: { warriorReduce: 0.01 },
		antiMage: { mageReduce: 0.01 },
		antiRanger: { rangerReduce: 0.01 },
		antiAssassin: { assassinReduce: 0.01 },
		heartOfCrystal: { 'Seal of LightImmune': 0.01, ShapeshiftImmune: 0.01 },
		immortalRoar: { TauntImmune: 0.01, DazzleImmune: 0.01 },
		spellOfAgility: { petrifyImmune: 0.01, twineImmune: 0.01, HorrifyImmune: 0.01 },
		blessingOfPurification: { stunImmune: 0.01, freezeImmune: 0.01, SilenceImmune: 0.01 },
	},
};