var guildTech = {
  "Warrior": {
    hpPercent: {hpPercent: 0.005},
    attackPercent: {attackPercent: 0.005},
    crit: {crit: 0.005},
    block: {block: 0.005},
    skillDamage: {skillDamage: 0.01},
    speed: {speed: 4},
    constitution: {hpPercent: 0.01, attackPercent: 0.01},
    mind: {hpPercent: 0.01, skillDamage: 0.01},
    antiMage: {mageReduce: 0.01},
    antiRanger: {rangerReduce: 0.01},
    antiAssassin: {assassinReduce: 0.01},
    antiPriest: {priestReduce: 0.01},
    stunImmune: {stunImmune: 0.01},
    freezeImmune: {freezeImmune: 0.01},
    petrifyImmune: {petrifyImmune: 0.01},
    twineImmune: {twineImmune: 0.01}
  },
  "Mage": {
    hpPercent: {hpPercent: 0.005},
    attackPercent: {attackPercent: 0.005},
    crit: {crit: 0.005},
    precision: {precision: 0.005},
    skillDamage: {skillDamage: 0.01},
    speed: {speed: 4},
    constitution: {hpPercent: 0.01, attackPercent: 0.01},
    mind: {hpPercent: 0.01, skillDamage: 0.01},
    antiWarrior: {warriorReduce: 0.01},
    antiRanger: {rangerReduce: 0.01},
    antiAssassin: {assassinReduce: 0.01},
    antiPriest: {priestReduce: 0.01},
    stunImmune: {stunImmune: 0.01},
    freezeImmune: {freezeImmune: 0.01},
    petrifyImmune: {petrifyImmune: 0.01},
    twineImmune: {twineImmune: 0.01}
  },
  "Ranger": {
    hpPercent: {hpPercent: 0.005},
    attackPercent: {attackPercent: 0.005},
    block: {block: 0.005},
    precision: {precision: 0.005},
    skillDamage: {skillDamage: 0.01},
    speed: {speed: 4},
    constitution: {hpPercent: 0.01, attackPercent: 0.01},
    mind: {hpPercent: 0.01, skillDamage: 0.01},
    antiWarrior: {warriorReduce: 0.01},
    antiMage: {mageReduce: 0.01},
    antiAssassin: {assassinReduce: 0.01},
    antiPriest: {priestReduce: 0.01},
    stunImmune: {stunImmune: 0.01},
    freezeImmune: {freezeImmune: 0.01},
    petrifyImmune: {petrifyImmune: 0.01},
    twineImmune: {twineImmune: 0.01}
  },
  "Assassin": {
    hpPercent: {hpPercent: 0.005},
    critDamage: {critDamage: 0.005},
    crit: {crit: 0.005},
    armorBreak: {armorBreak: 0.005},
    skillDamage: {skillDamage: 0.01},
    speed: {speed: 4},
    constitution: {hpPercent: 0.01, attackPercent: 0.01},
    mind: {hpPercent: 0.01, skillDamage: 0.01},
    antiWarrior: {warriorReduce: 0.01},
    antiMage: {mageReduce: 0.01},
    antiRanger: {rangerReduce: 0.01},
    antiPriest: {priestReduce: 0.01},
    stunImmune: {stunImmune: 0.01},
    freezeImmune: {freezeImmune: 0.01},
    petrifyImmune: {petrifyImmune: 0.01},
    twineImmune: {twineImmune: 0.01}
  },
  "Priest": {
    hpPercent: {hpPercent: 0.005},
    block: {block: 0.005},
    crit: {crit: 0.005},
    speed: {speed: 2},
    skillDamage: {skillDamage: 0.01},
    speed2: {speed: 1, attackPercent: 0.005},
    constitution: {hpPercent: 0.01, attackPercent: 0.01},
    mind: {hpPercent: 0.01, skillDamage: 0.01},
    antiWarrior: {warriorReduce: 0.01},
    antiMage: {mageReduce: 0.01},
    antiRanger: {rangerReduce: 0.01},
    antiAssassin: {assassinReduce: 0.01},
    stunImmune: {stunImmune: 0.01},
    freezeImmune: {freezeImmune: 0.01},
    petrifyImmune: {petrifyImmune: 0.01},
    twineImmune: {twineImmune: 0.01}
  }
};